# Generated by Django 4.1.2 on 2022-12-05 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryIHA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='iha',
            name='month',
        ),
        migrations.RemoveField(
            model_name='iha',
            name='price',
        ),
        migrations.RemoveField(
            model_name='iha',
            name='product',
        ),
        migrations.AddField(
            model_name='iha',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ihas', to='core.categoryiha'),
            preserve_default=False,
        ),
    ]
