# Generated by Django 4.1.2 on 2022-12-06 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoryiha_remove_iha_month_remove_iha_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Period',
            new_name='Marka',
        ),
        migrations.RenameField(
            model_name='marka',
            old_name='muddet',
            new_name='name',
        ),
        migrations.AddField(
            model_name='iha',
            name='markas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ihas', to='core.marka'),
            preserve_default=False,
        ),
    ]
