# Generated by Django 4.1.2 on 2022-12-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_period_marka_rename_muddet_marka_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iha',
            name='marka',
        ),
        migrations.AddField(
            model_name='iha',
            name='slug',
            field=models.SlugField(default='sadasd', verbose_name='slug'),
            preserve_default=False,
        ),
    ]
