# Generated by Django 4.1.2 on 2022-12-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_iha_marka_iha_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iha',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='slug'),
        ),
    ]
