# Generated by Django 4.1.2 on 2022-12-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_iha_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='iha',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=12.12, max_digits=5, verbose_name='Weight'),
            preserve_default=False,
        ),
    ]
