# Generated by Django 4.1.2 on 2022-12-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_iha_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iha',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Weight'),
        ),
    ]
